### PR TITLE
chore: Bump version to 6.0.9

### PR DESCRIPTION
**Pull request by rb-union**
Bump version to 6.0.9
PR:
* https://github.com/linuxdeepin/deepin-reader/pull/97
* https://github.com/linuxdeepin/deepin-reader/pull/98

Log: Bump version to 6.0.9

### CODE REVIEW

**Review by myk1343 — APPROVED** [review]
/+1

**Review by starhcq — APPROVED** [review]
/+1

**Review by lzwind — APPROVED** [review]

**Pull request merged**
