### PR TITLE
feat: zpd定制需求，复制拦截，关闭上报

### PR DESCRIPTION
**Pull request by hundundadi**
Description: zpd定制需求，复制拦截，关闭上报

Log: zpd定制需求，复制拦截，关闭上报

Task: https://pms.uniontech.com/task-view-279165.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
