### PR TITLE
fix: 修复紧凑模式下文档查看器顶部控件显示问题

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 1060新增紧凑模式，未进行适配

Log: 修复紧凑模式下文档查看器顶部控件显示问题

Bug: https://pms.uniontech.com/bug-view-202837.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
