### PR TITLE
fix: 修复文档查看无法打开网站链接及添加一些关键日志打印

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 由于网站链接路径转换错误

Log: 修复文档查看无法打开网站链接及添加一些关键日志打印

Bug: https://pms.uniontech.com/bug-view-154747.html
     https://pms.uniontech.com/bug-view-154749.html

### CODE REVIEW

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
