### PR TITLE
fix: 修复文档查看器增大缩放比例后鼠标无法跟随滚动查看文字

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 修复文档查看器增大缩放比例后鼠标无法跟随滚动查看文字

Log: 修复文档查看器增大缩放比例后鼠标无法跟随滚动查看文字

Bug: https://pms.uniontech.com/bug-view-166397.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
