### PR TITLE
fix: 修复文档查看器的日志记录了用户复制内容的问题

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 修复文档查看器的日志记录了用户复制内容的问题

Log: 修复文档查看器的日志记录了用户复制内容的问题

Bug: https://pms.uniontech.com/bug-view-164929.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Pull request merged**
