### PR TITLE
fix: 修复当书签与超链接重叠时，点击书签，会触发超链接

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 未对书签区域做屏蔽

Log: 修复当书签与超链接重叠时，点击书签，会触发超链接

Bug: https://pms.uniontech.com/bug-view-164267.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
